### ISSUE TITLE
SMS sniff

### ISSUE THREAD

**Issue by alphafox02** [ninjhacks/gsmevil2#6]
Mainly just curious for lab purposes and learning. 

I’ve tested gsmevil2 against YateBTS and have not seen any SMS captured. 

However the following Wireshark filters work when enabling the Wireshark tap in yate. Wondered if you’d actually seen the SMS sniff work in your testing on appropriate setup conditions?

Only GSM: gsmtap && !icmp

Only paging activity: gsmtap.chan_type == CCCH && !icmp

Only SMS (Uplink / Downlink): gsm_a.dtap.msg_sms_type == 0x01

Only SMS from originator 12345: gsm_sms.tp-oa == "12345"

Only SMS ack from subscriber: gsm_a.rp.msg_type == 0x02

**Comment by ninjhacks** [comment]
I build this tool for my own testing and i successfully captured sms because of not any encryption in my case. if tool see any sms packet on the network it's will show you it's used wireshark package that's mean if you see SMS packet in Wireshark then for sure you will going to see in this tool also.

**Comment by alphafox02** [comment]
Okay. I’ll check again. If I see it in wireshark then I’ll expect to see it with the SMS sniff. Thanks

**Comment by demontolivo** [comment]
Pls can I use this tool and sniff sms from a number outside my country or is it just within my region or country
